---
- name: Include variables suitable to our OS Family
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include tasks suitable to our OS Family
  include: "{{ ansible_os_family }}.yml"

- name: Configure Rsyslog
  template: 
    src: rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode : 0644
  notify: restart_rsyslog
